---
plugin: rest
contentType: application/json
resources:
  - path: "/cats/{id}"
    type: array
    response:
      file: cats.json
  - path: "/dogs/{id}"
    type: array
    response:
      file: dogs.json
