openapi: "3.1.0"
info:
  version: 1.0.0
  title: User service
  license:
    name: MIT
    identifier: MIT
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: [integer]
            format: int64
      responses:
        '200':
          description: users response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: [object]
      required:
        - id
        - firstName
        - lastName
        - email
        - username
        - address
      properties:
        id:
          type: [string]
          format: uuid
        firstName:
          type: [string]
        lastName:
          type: [string]
        email:
          type: [string]
          format: email
        username:
          type: [string]
        address:
          $ref: "#/components/schemas/Address"
        favouriteColour:
          type: [string]
          x-fake-data: "color.name"
    Address:
      type: [object]
      required:
        - street
        - city
        - postcode
      properties:
        street:
          type: [string]
        city:
          type: [string]
        postcode:
          type: [string]
