plugin: rest

resources:
- path: "/pets"
  method: "OPTIONS"
  response:
    statusCode: 200
    headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type, Authorization"
      Access-Control-Max-Age: "60"

- path: "/pets"
  method: "POST"
  response:
    content: Received name ${context.request.queryParams.name}
    template: true
    headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type, Authorization"
      Access-Control-Max-Age: "60"
