plugin: "openapi"
specFile: "openapi3-with-multiple-status-codes.yaml"

resources:
  - path: "/pets"
    method: "get"
    response:
      statusCode: 200

  # handles GET /pets?page=1
  - path: "/pets"
    method: "get"
    queryParams:
      page: 1
    response:
      statusCode: 204

  - path: "/pets"
    method: "post"
    response:
      statusCode: 201

  - path: "/pets/{petId}"
    method: "put"
    response:
      statusCode: 202

  # handles GET /pets/10
  - path: "/pets/{petId}"
    method: GET
    pathParams:
      petId: 10
    response:
      statusCode: 401
      content: "You do not have permission to view this pet."

  # handles PUT /pets/{petId} with a request header 'X-Pet-Username: foo'
  - path: "/pets/{petId}"
    method: PUT
    requestHeaders:
      X-Pet-Username: foo
    response:
      statusCode: 409
      content: "Username already exists."
