plugins {
    id 'java-library'
    id 'com.gradleup.shadow'
}

dependencies {
    implementation 'net.bytebuddy:byte-buddy-dep:1.18.11'
    implementation 'net.bytebuddy:byte-buddy-agent:1.18.11'
}

jar {
    manifest {
        attributes 'Premain-Class': 'io.gatehill.imposter.perf.Agent'
    }
}

shadowJar {
    archiveFileName.set('imposter-perf-monitor.jar')
}
