plugin: rest

resources:
- method: GET
  path: /example
  response:
    file: simpleTemplate.txt
    template: true

- method: PUT
  path: /pets/{petId}
  capture:
    petId:
      pathParam: petId
      store: request
  response:
    file: petTemplate.txt
    template: true

- method: POST
  path: /users
  capture:
    address:
      jsonPath: $.address
      store: templateTest
  response:
    file: jsonPathTemplate.txt
    template: true
