plugin: rest

resources:
  # Example using allOf - all expressions must match
  - method: POST
    path: /validate-all
    allOf:
      - expression: "${context.request.headers.Authorization}"
        operator: Matches
        value: "Bearer .*"
      - expression: "${context.request.headers.X-API-Version}"
        operator: EqualTo
        value: "2024-01"
    response:
      statusCode: 200
      content: "All validations passed"

  # Example using anyOf - at least one expression must match
  - method: POST
    path: /validate-any
    anyOf:
      - expression: "${context.request.headers.X-Legacy-Auth}"
        operator: EqualTo
        value: "legacy-token"
      - expression: "${context.request.headers.Authorization}"
        operator: Matches
        value: "Bearer .*"
    response:
      statusCode: 200
      content: "Authentication valid"

  # Example combining request body and expression matching
  - method: POST
    path: /orders
    requestBody:
      jsonPath: $.type
      value: "express"
    allOf:
      - expression: "${context.request.headers.X-Priority}"
        operator: EqualTo
        value: "high"
      - expression: "${context.request.queryParams.region}"
        operator: Contains
        value: "EU"
    response:
      statusCode: 202
      content: "Express order accepted"
