name: CI
on: [ push ]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      effective-branch: ${{ steps.git-meta.outputs.EFFECTIVE_BRANCH }}
    steps:
      - uses: actions/checkout@v4
      - name: Determine effective branch
        id: git-meta
        run: |
          EFFECTIVE_BRANCH_NAME="$( ./scripts/get-effective-branch.sh )"
          echo "EFFECTIVE_BRANCH=${EFFECTIVE_BRANCH_NAME}" >> $GITHUB_OUTPUT

  validate:
    needs: [setup]
    uses: ./.github/workflows/validate.yaml

  dist:
    needs: [setup, validate]
    uses: ./.github/workflows/dist.yaml
    with:
      effective-branch: ${{ needs.setup.outputs.effective-branch }}
    secrets: inherit

  distroless:
    needs: [setup, validate]
    uses: ./.github/workflows/distroless.yaml
    with:
      effective-branch: ${{ needs.setup.outputs.effective-branch }}
    secrets: inherit
