name: Cut release
on: [ workflow_dispatch ]

permissions:
  checks: write
  contents: write

jobs:
  cut-release:
    outputs:
      version: ${{ steps.since.outputs.CURRENT_VERSION }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SINCE_VERSION: "0.15.5"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure git
        run: |
          git config user.name "Imposter release bot"
          git config user.email "release-bot@imposter.sh"

      - name: Install since
        run: |
          cd "$( mktemp -d )"
          curl --fail -L -o since.tar.gz https://github.com/release-tools/since/releases/download/v${SINCE_VERSION}/since_${SINCE_VERSION}_linux_amd64.tar.gz
          tar xvf since.tar.gz
          cp since /usr/local/bin

      - name: Cut release
        id: since
        run: |
          since project release
          echo "CURRENT_VERSION=$( since project version --current --log-level=info )" >> $GITHUB_OUTPUT

      - name: Push changes
        run: git push origin main --tags

  ci:
    needs: [cut-release]
    uses: ./.github/workflows/pipeline.yaml
    with:
      effective-branch: main
      release: true
      version: ${{ needs.cut-release.outputs.version }}
    secrets: inherit
