name: Distribute
on:
  workflow_call:
    inputs:
      effective-branch:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    permissions:
      contents: write
    env:
      AWS_REGION: "eu-west-1"
      CONTAINER_BUILDER: "buildx"
      SINCE_VERSION: "0.14.2"
      TESTCONTAINERS_RYUK_DISABLED: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Install since
        if: ${{ (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop') }}
        run: |
          cd "$( mktemp -d )"
          curl --fail -L -o since.tar.gz https://github.com/release-tools/since/releases/download/v${SINCE_VERSION}/since_${SINCE_VERSION}_linux_amd64.tar.gz
          tar xvf since.tar.gz
          cp since /usr/local/bin

      - name: Write changelog
        if: ${{ (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop') }}
        run: |
          mkdir -p build
          since changelog extract -q > build/CHANGES.md
          cat build/CHANGES.md

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up build environment
        run: |
          chmod +x ./scripts/*.sh
          # Disable gradle daemon
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Build distributions
        run: ./gradlew dist --stacktrace -xtest

      - name: Integration test
        run: |
          ./scripts/docker-build.sh -p false dev
          ./scripts/integration-tests.sh outofcoffee/imposter:dev
          ./scripts/integration-tests.sh outofcoffee/imposter-all:dev

      - name: Build and push Docker images
        id: docker-build
        if: ${{ (startsWith(github.ref, 'refs/tags/') || inputs.effective-branch == 'develop') }}
        run: |
          case ${{ inputs.effective-branch }} in
          develop)
            ./scripts/docker-build.sh -p true beta
            ;;

          main)
            CURRENT_VERSION="$( git describe --tags --exact-match )"
            if [[ "${CURRENT_VERSION:0:1}" == "v" ]]; then
                CURRENT_VERSION="$( echo ${CURRENT_VERSION} | cut -c 2- )"
            fi
            ./scripts/docker-build.sh -p true "${CURRENT_VERSION}"
            ./scripts/docker-build.sh -p true "latest"
            ;;

          release/2.x)
            CURRENT_VERSION="$( git describe --tags --exact-match )"
            if [[ "${CURRENT_VERSION:0:1}" == "v" ]]; then
                CURRENT_VERSION="$( echo ${CURRENT_VERSION} | cut -c 2- )"
            fi
            ./scripts/docker-build.sh -p true "${CURRENT_VERSION}"
            ;;
          esac
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release Java assets
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/github-release.js')
            await script({github, context}, [
              'main',
              './distro/awslambda/build/distributions/imposter-awslambda.zip',
              './mock/hbase/build/libs/imposter-plugin-mock-hbase.jar',
              './mock/sfdc/build/libs/imposter-plugin-mock-sfdc.jar',
              './mock/wiremock/build/libs/imposter-plugin-wiremock.jar',
              './scripting/graalvm/build/distributions/imposter-plugin-js-graal.zip',
              './store/dynamodb/build/libs/imposter-plugin-store-dynamodb.jar',
              './store/graphql/build/libs/imposter-plugin-store-graphql.jar',
              './store/redis/build/libs/imposter-plugin-store-redis.jar',
              './lib/fake-data/build/libs/imposter-plugin-fake-data.jar',
            ])

      - name: Publish Maven artifacts
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew publish --info --stacktrace
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
