name: Distroless
on:
  workflow_call:
    inputs:
      effective-branch:
        required: true
        type: string
      release:
        required: true
        type: boolean
    secrets:
      DOCKER_USERNAME:
        # only needed for release builds
        required: false
      DOCKER_PASSWORD:
        # only needed for release builds
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTAINER_BUILDER: "buildx"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up build environment
        run: |
          chmod +x ./scripts/*.sh
          # Disable gradle daemon
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - name: Build distributions
        run: ./gradlew :distro:distro-core:installDist --stacktrace -xtest

      - name: Build and push Docker images
        id: docker-build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          case ${{ inputs.effective-branch }} in
          develop)
            ./scripts/docker-build.sh -p true -i distroless -b false beta
            ;;

          main)
            CURRENT_VERSION="$( git describe --tags --exact-match )"
            if [[ "${CURRENT_VERSION:0:1}" == "v" ]]; then
                CURRENT_VERSION="$( echo ${CURRENT_VERSION} | cut -c 2- )"
            fi
            ./scripts/docker-build.sh -p true -i distroless -b false "${CURRENT_VERSION}"
            ./scripts/docker-build.sh -p true -i distroless -b false "latest"
            ;;
          esac
