name: Docs site
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.x

      - name: Install mkdocs
        env:
          PIP_CONSTRAINT: ./docs/infrastructure/constraints.txt
        run: pip install -r ./docs/infrastructure/requirements.txt

      - name: Build static site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        if: ${{ github.ref_name == 'main' }}
        run: mkdocs gh-deploy --force
